export const siteConfig = {
  name: "Aditya Birla — AI Consultant & Full Stack Java Developer",
  title: "AI Consultant & Full Stack Java Developer | Aditya Birla",
  description: "Aditya Birla is an AI Consultant and Full Stack Java Developer specializing in Generative AI solutions, RAG systems, multi-agent frameworks, and enterprise Spring Boot microservices. Available for AI consulting engagements worldwide.",
  // ← Replace with your real production domain once available (no trailing slash)
  url: "https://adityatech-ai.vercel.app",
  locale: "en_US",
  twitterHandle: "@yourhandle",
  keywords: [
    "Aditya Birla AI consultant",
    "Aditya Birla",
    "AI consultant India",
    "Generative AI consultant",
    "AI consulting services",
    "RAG systems developer",
    "LLM engineer",
    "AI solutions engineer",
    "full stack Java developer India",
    "Spring Boot developer",
    "Java developer",
    "microservices architect",
    "freelance AI consultant",
    "AI agent developer",
    "enterprise AI consulting",
  ],
  author: {
    name: "Aditya Birla",
    email: "aditya.aiconsultant04@gmail.com",
    linkedin: "https://linkedin.com/in/yourhandle",
    github: "https://github.com/yourhandle",
    // ← Drop your photo URL here (local: "/avatar.jpg"  or  external: "https://...")
    avatarUrl: "https://ik.imagekit.io/chedcztb6/file_00000000db407208a5fed573a060a5b3.png?updatedAt=1781590075933&ik-s=5f0e8f73545ea021c3eff0fe47d5e091432210d5",
    // WhatsApp number in international format without +, spaces or dashes
    whatsapp: "917441176988",
    whatsappMessage: "Hi Aditya, I'd like to discuss a project with you.",
  },
};

export const experiences = [
  {
    id: "exp-1",
    title: "Software Engineer",
    company: "Accenture",
    duration: "1.5 years",
    startDate: "Jan 2023",
    endDate: "Jul 2024",
    location: "India",
    type: "full-time",
    description: "Designed and delivered high-throughput enterprise backend systems serving millions of requests per day, contributing to a large-scale banking and financial services platform.",
    responsibilities: [
      "Architected and developed RESTful microservices using Spring Boot 3.x and Java 17, deployed on AWS ECS",
      "Designed domain-driven service boundaries across a distributed system of 12+ independent services",
      "Built asynchronous event-driven pipelines using Apache Kafka for real-time transaction processing",
      "Collaborated with cross-functional teams of 15+ engineers to deliver quarterly platform releases",
    ],
    technologies: ["Java 17","Spring Boot 3","Apache Kafka","PostgreSQL","Oracle DB","AWS ECS","Docker","Jenkins CI/CD","Redis","REST APIs"],
    achievements: [
      { metric: "40%", description: "Reduction in API latency via connection pooling and N+1 query elimination" },
      { metric: "99.95%", description: "Service uptime maintained across 3 production deployments" },
      { metric: "12+", description: "Microservices designed and delivered in a distributed financial platform" },
      { metric: "60%", description: "Faster CI pipeline through parallelized test execution and layer caching" },
    ],
  },
  {
    id: "exp-2",
    title: "Software Engineer",
    company: "TCS",
    duration: "1 year",
    startDate: "Jan 2022",
    endDate: "Jan 2023",
    location: "India",
    type: "full-time",
    description: "Built full-stack enterprise features for a global retail client, delivering scalable backend APIs and performant React frontends within an agile team of 20+ engineers.",
    responsibilities: [
      "Developed Spring Boot REST APIs consumed by React frontend applications serving 500K+ daily active users",
      "Implemented JWT-based authentication and RBAC authorization for a multi-tenant SaaS platform",
      "Optimized Oracle DB queries reducing report generation time for large enterprise datasets",
      "Integrated third-party payment gateways and logistics APIs with robust error handling and retry logic",
    ],
    technologies: ["Java 11","Spring Boot 2","React","TypeScript","Oracle DB","AWS EC2","Maven","Git","JUnit 5","Mockito"],
    achievements: [
      { metric: "55%", description: "Improvement in database query performance via index optimization and query rewriting" },
      { metric: "3x", description: "Faster report generation through query optimization and result caching" },
      { metric: "98%", description: "Unit test coverage achieved across all new service modules" },
      { metric: "0", description: "Critical production incidents over 6 consecutive months of delivery" },
    ],
  },
];

export const projects = [
  {
    id: "proj-1",
    title: "EnterpriseRAG — Knowledge Intelligence Platform",
    tagline: "Production-grade RAG system for enterprise knowledge retrieval",
    problem: "A financial services client needed their 50,000+ internal documents — policies, compliance guides, contracts — to be instantly queryable by employees with accurate, cited responses.",
    solution: "Built a multi-tenant Retrieval-Augmented Generation platform with hierarchical chunking, hybrid BM25 + semantic search, re-ranking, and a Spring Boot API layer.",
    architecture: "Spring Boot 3 API → Document Ingestion Pipeline → pgvector (PostgreSQL) → Hybrid Retrieval Engine → LLM Orchestration (LangChain4j) → Response with Citations",
    technologies: ["Java 21","Spring Boot 3","LangChain4j","pgvector","OpenAI API","PostgreSQL","Redis","Docker","AWS ECS","React","TypeScript"],
    impact: [
      "Reduced document search time from 45 minutes to under 8 seconds",
      "Achieved 94.2% answer accuracy on internal benchmark dataset",
      "Onboarded 1,200+ enterprise users in first month post-launch",
      "Eliminated 80% of repetitive support tickets through intelligent self-service",
    ],
    github: "https://github.com/yourhandle/enterprise-rag",
    demo: "https://demo.enterpriserag.dev",
    featured: true,
    category: "ai",
    year: 2024,
  },
  {
    id: "proj-2",
    title: "DistributedCommerce — Microservices E-Commerce Platform",
    tagline: "Cloud-native e-commerce engine built for scale",
    problem: "A mid-market retailer outgrew their monolithic order management system — experiencing 6-hour deployment windows, cascading failures, and inability to scale individual bottlenecks.",
    solution: "Re-architected the platform into 8 domain-driven microservices with event sourcing, Saga choreography for distributed transactions, and a comprehensive observability stack.",
    architecture: "API Gateway → 8 Domain Services (Order, Inventory, Payment, Shipping, Notification, User, Catalog, Analytics) → Apache Kafka event bus → Individual PostgreSQL databases → Redis cache layer",
    technologies: ["Java 17","Spring Boot 3","Apache Kafka","PostgreSQL","Redis","Docker","Kubernetes (EKS)","AWS","Prometheus","Grafana"],
    impact: [
      "Reduced deployment window from 6 hours to 12 minutes with zero-downtime blue-green deploys",
      "Platform handles 100,000+ concurrent users with horizontal pod autoscaling",
      "99.99% order processing uptime achieved via Saga pattern and idempotent consumers",
      "Individual service deployments cut time-to-production by 78% per team",
    ],
    github: "https://github.com/yourhandle/distributed-commerce",
    featured: true,
    category: "microservices",
    year: 2024,
  },
  {
    id: "proj-3",
    title: "IntelliAgent — Autonomous AI Workflow Engine",
    tagline: "Multi-agent orchestration framework for complex business workflows",
    problem: "Enterprise operations teams spent 60% of their time on repetitive data gathering, summarization, and escalation workflows that required reasoning across multiple internal systems.",
    solution: "Built a multi-agent orchestration platform with specialized agents (Researcher, Analyst, Executor, Reviewer) using a custom Spring Boot orchestration layer.",
    architecture: "Agent Orchestrator → Tool Registry (APIs, DBs, File Systems) → Specialized Agents → State Machine → Output Validator → Human-in-the-loop Checkpoint",
    technologies: ["Java 21","Spring Boot 3","LangChain4j","GPT-4o","Spring State Machine","PostgreSQL","Redis Streams","React","WebSockets","AWS Lambda"],
    impact: [
      "Automated 23 distinct enterprise workflows previously requiring manual coordination",
      "Reduced average workflow completion time by 85%",
      "Processes 10,000+ automated tasks per day with full audit trails",
      "ROI of 340% achieved within 8 months of deployment",
    ],
    github: "https://github.com/yourhandle/intelli-agent",
    featured: true,
    category: "ai",
    year: 2024,
  },
  {
    id: "proj-4",
    title: "CloudSync — Real-Time Collaboration API",
    tagline: "Enterprise-grade real-time sync infrastructure",
    problem: "Teams using existing collaboration tools reported 3–8 second sync delays that disrupted live editing sessions and created document conflict nightmares.",
    solution: "Designed a WebSocket-based CRDT synchronization engine backed by a Spring Boot reactive API and a custom operational transform layer.",
    architecture: "React Client → WebSocket Gateway → Spring WebFlux API → CRDT Merge Engine → Redis Pub/Sub → PostgreSQL Event Store",
    technologies: ["Java 17","Spring WebFlux","WebSockets","Redis Pub/Sub","PostgreSQL","React","TypeScript","Docker","AWS"],
    impact: [
      "Sub-100ms sync latency achieved across geographically distributed clients",
      "Supports 500+ simultaneous document editors per instance",
      "Zero data loss across 200,000+ collaborative sessions in production",
    ],
    github: "https://github.com/yourhandle/cloudsync",
    featured: false,
    category: "enterprise",
    year: 2023,
  },
  {
    id: "proj-5",
    title: "SecureVault — Enterprise Identity & Access Management",
    tagline: "Zero-trust IAM platform for multi-tenant SaaS environments",
    problem: "A SaaS provider with 300+ enterprise clients lacked centralized identity governance — each tenant managed their own users in isolation, creating audit nightmares, inconsistent RBAC enforcement, and no SSO capability across their product suite.",
    solution: "Designed and built a centralised IAM platform with OIDC/OAuth2 flows, SAML 2.0 federation for enterprise SSO, fine-grained ABAC policy engine, and a self-service admin portal for tenant administrators.",
    architecture: "API Gateway → Spring Security OAuth2 Authorization Server → Policy Decision Point (ABAC Engine) → SAML/OIDC Federation Layer → Tenant Config Store (PostgreSQL) → Audit Event Stream (Kafka) → SIEM Integration",
    technologies: ["Java 21", "Spring Boot 3", "Spring Security", "OAuth2", "SAML 2.0", "PostgreSQL", "Apache Kafka", "React", "TypeScript", "Docker", "AWS ECS"],
    impact: [
      "Unified identity management across 300+ enterprise tenants on a single platform",
      "SSO adoption reduced average login friction by 65% per user survey",
      "Achieved SOC 2 Type II compliance within 6 months of platform launch",
      "Eliminated 100% of manual user-provisioning tickets via SCIM 2.0 automation",
    ],
    github: "https://github.com/yourhandle/securevault",
    demo: null,
    featured: false,
    category: "enterprise",
    year: 2023,
  },
];

export const skillCategories = [
  {
    id: "backend",
    label: "Enterprise Backend",
    description: "Building reliable, high-throughput backend systems",
    icon: "server",
    skills: [
      { name: "Java 21 / 17", level: "core" },
      { name: "Spring Boot 3", level: "core" },
      { name: "Spring Security", level: "core" },
      { name: "Spring Data JPA", level: "core" },
      { name: "Microservices", level: "core" },
      { name: "Apache Kafka", level: "core" },
      { name: "REST API Design", level: "core" },
      { name: "System Design", level: "proficient" },
      { name: "PostgreSQL", level: "core" },
      { name: "Oracle DB", level: "proficient" },
      { name: "Redis", level: "proficient" },
      { name: "Hibernate ORM", level: "core" },
    ],
  },
  {
    id: "frontend",
    label: "Frontend Engineering",
    description: "Crafting performant, accessible user interfaces",
    icon: "monitor",
    skills: [
      { name: "React 18", level: "proficient" },
      { name: "Next.js 14", level: "proficient" },
      { name: "TypeScript", level: "proficient" },
      { name: "Tailwind CSS", level: "proficient" },
      { name: "Framer Motion", level: "familiar" },
      { name: "REST / GraphQL", level: "proficient" },
    ],
  },
  {
    id: "cloud",
    label: "Cloud & DevOps",
    description: "Infrastructure, deployment, and operational excellence",
    icon: "cloud",
    skills: [
      { name: "AWS (ECS, EC2, S3, RDS, Lambda)", level: "proficient" },
      { name: "Docker", level: "core" },
      { name: "Kubernetes (EKS)", level: "proficient" },
      { name: "Jenkins / GitHub Actions", level: "proficient" },
      { name: "Terraform", level: "familiar" },
      { name: "Prometheus + Grafana", level: "proficient" },
    ],
  },
  {
    id: "ai",
    label: "AI Engineering",
    description: "Building intelligent, reasoning-capable software systems",
    icon: "brain",
    skills: [
      { name: "Generative AI / LLMs", level: "proficient" },
      { name: "RAG Systems", level: "proficient" },
      { name: "LangChain4j", level: "proficient" },
      { name: "OpenAI / Anthropic API", level: "proficient" },
      { name: "Vector Databases", level: "proficient" },
      { name: "AI Agents", level: "proficient" },
      { name: "Prompt Engineering", level: "core" },
      { name: "Semantic Search", level: "proficient" },
    ],
  },
];

export const testimonials = [
  {
    id: "test-1",
    name: "Pandit Aman Bhatore",
    role: "Vastu Shastra Consultant",
    company: "VastuByAman",
    content: "The website exceeded every expectation. The booking modal is seamless, animations feel premium, and clients now reach me directly online. My consultation inquiries doubled within the first month of going live.",
    outcome: "Consultation bookings doubled within the first month of launch.",
    rating: 5,
  },
  {
    id: "test-2",
    name: "Goutam Birla",
    role: "Owner",
    company: "Ramira Foods",
    content: "Before this, we were managing orders manually over WhatsApp. Now every order lands instantly on Telegram with full customer details. It's fast, reliable, and has genuinely transformed how we run the business.",
    outcome: "Eliminated manual order tracking — every order delivered instantly.",
    rating: 5,
  },
  {
    id: "test-3",
    name: "Goutam Birla",
    role: "Founder & Lead Artist",
    company: "SecondLayer Tattoo",
    content: "My studio finally has an online presence worthy of the work we do. The site looks stunning, loads fast, and clients are finding us on Google now. Bookings through the website have been a game changer.",
    outcome: "Studio now ranks locally on Google — walk-in and online bookings up.",
    rating: 5,
  },
];

export const blogTopics = [
  { category: "Java & Spring Boot", topics: [
    "Spring Boot 3 Virtual Threads with Project Loom: A Production Guide",
    "Building Zero-Downtime Deployments with Spring Boot and Kubernetes",
    "Advanced Spring Security: Implementing OAuth2 with Custom Claims",
    "Spring Boot Native Images with GraalVM: Performance Deep Dive",
    "Mastering @Transactional Pitfalls in Spring Data JPA",
  ]},
  { category: "Microservices & System Design", topics: [
    "Saga Pattern vs Two-Phase Commit: When to Use Each",
    "Event Sourcing with Apache Kafka and Spring Boot",
    "Circuit Breakers in Production: Resilience4j Configuration Guide",
    "API Gateway Design Patterns for Microservices Architectures",
    "Database Per Service Pattern: Practical Implementation Guide",
  ]},
  { category: "AI Engineering", topics: [
    "Building Production RAG Systems: Beyond the Hello World Tutorial",
    "Evaluating RAG Quality: RAGAS Metrics and What They Actually Mean",
    "LangChain4j vs LangChain Python: An Enterprise Java Developer's Perspective",
    "Eliminating LLM Hallucinations with Structured Output and Validation",
    "Multi-Agent Systems with Spring Boot: Architecture and Patterns",
    "Vector Database Comparison: pgvector vs Pinecone vs Weaviate for Java Apps",
  ]},
];
